name: bus_finder_staff_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  signalr_netcore: ^1.3.5
  web_socket_channel: 3.0.3
  logging: ^1.1.0

  cupertino_icons: ^1.0.8
  flutter_polyline_points: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_staff.png
    - assets/images/logo.png
    - assets/images/sample_map.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
